# Generated by Django 5.2.4 on 2025-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Tools', 'Tools'), ('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Others', 'Others')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
