# Generated by Django 5.2.4 on 2025-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marketplaceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_images/'),
        ),
        migrations.AlterField(
            model_name='marketplaceitem',
            name='category',
            field=models.CharField(choices=[('Tools', 'Tools'), ('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Irrigation', 'Irrigation'), ('Machinery', 'Machinery'), ('Others', 'Others')], max_length=20),
        ),
    ]
