# Generated by Django 5.2.4 on 2025-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketplaceitem_image_alter_marketplaceitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Soil', 'Soil'), ('Water', 'Water'), ('Pest', 'Pest'), ('Climate', 'Climate'), ('General', 'General')], default='General', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
